os:
  - linux
services:
  - docker
language: node_js
node_js:
  - '18.18.2'
cache:
  directories:
    - node
    - node_modules
    - $HOME/.m2
env:
  global:
    - NODE_VERSION=18.18.2
    - JHI_JDK=17
    - SPRING_OUTPUT_ANSI_ENABLED=ALWAYS
    - SPRING_JPA_SHOW_SQL=false
    - JHI_DISABLE_WEBPACK_LOGS=true
    - NG_CLI_ANALYTICS="false"
    - MAVEN_USER_HOME=$HOME/.m2/repository/
    - CYPRESS_ENABLE_RECORD: false
before_install:
  - |
    echo '*** Using OpenJDK 17 by default'
    sudo apt-get update -q
    sudo apt-get install -y openjdk-17-jdk
    sudo update-java-alternatives -s java-1.17.0-openjdk-amd64
    java -version
  - sudo /etc/init.d/mysql stop
  - sudo /etc/init.d/postgresql stop
  - nvm install $NODE_VERSION
  - npm install -g npm
  - node -v
  - npm -v
install:
  - npm install
script:
  - chmod +x mvnw
  - npm run ci:backend:test
  - npm run ci:frontend:test
  - npm run java:jar:prod
  - npm run ci:e2e:package
  - npm run ci:e2e:prepare
  - npm run ci:e2e:run
  - npm run ci:e2e:teardown

notifications:
  webhooks:
    on_success: change # options: [always|never|change] default: always
    on_failure: always # options: [always|never|change] default: always
    on_start: false # default: false
