version: '2'
include:
  - ./sonar.yml
services:
  jenkins:
    image: jenkins/jenkins:lts-jdk17
    ports:
      - 49001:8080
      - 50000:50000
    # uncomment for docker in docker
    #privileged: true
    volumes:
      # enable persistent volume (warning: make sure that the local jenkins_home folder is created)
      - ~/Applications/Jenkins:/var/jenkins_home
    # mount docker sock and binary for docker in docker (only works on linux)
    #- /var/run/docker.sock:/var/run/docker.sock
    #- /usr/bin/docker:/usr/bin/docker
